# MIPS assembly autogenerated by compiler
#
# @author Grant Yang
# @version $date

.macro push %reg
	sw %reg ($sp)
	addi $sp $sp -4
.end_macro
.macro pop %reg
	addi $sp $sp 4
	lw %reg ($sp)
.end_macro

.macro push.d %reg
	mfc1.d $t6 %reg
    sw $t6 -4($sp)
    sw $t7 ($sp)
    addi $sp $sp -8
.end_macro
.macro pop.d %reg
	addi $sp $sp 8
    lw $t6 -4($sp)
    lw $t7 ($sp)
    mtc1.d $t6 %reg
.end_macro
