// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: Desktop/ATNeural/jflex/JFlexScannerTemplate.flex

package scanner;

/**
* This file defines a simple lexer for the compilers course 2017-2018
* Comment this file
*/
import java.io.*;



@SuppressWarnings("fallthrough")
public class Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\5\u0100\1\u0200\1\u0300\1\u0100\5\u0400\1\u0500\1\u0600"+
    "\1\u0700\6\u0100\1\u0800\1\u0900\1\u0a00\1\u0b00\1\u0c00\1\u0d00"+
    "\3\u0100\1\u0e00\205\u0100\1\u0600\1\u0100\1\u0f00\1\u1000\1\u1100"+
    "\1\u1200\54\u0100\10\u1300\37\u0100\1\u0900\4\u0100\1\u1400\10\u0100"+
    "\1\u1500\2\u0100\1\u1600\1\u1700\1\u1200\1\u0100\1\u0500\1\u0100"+
    "\1\u1800\1\u1500\1\u0800\3\u0100\1\u1100\1\u1900\114\u0100\1\u1a00"+
    "\1\u1100\153\u0100\1\u1b00\11\u0100\1\u1c00\1\u1200\6\u0100\1\u1100"+
    "\u0f16\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\12\0\4\1\22\0\1\2\1\0\1\3\5\0\1\4"+
    "\1\5\2\0\1\6\1\2\1\7\1\0\1\10\1\11"+
    "\10\10\1\6\5\0\1\12\32\13\1\6\1\0\1\6"+
    "\1\0\1\13\1\0\1\14\3\13\1\15\1\16\5\13"+
    "\1\17\5\13\1\20\1\21\1\22\1\23\5\13\1\6"+
    "\1\0\1\6\7\0\1\1\u01da\0\12\24\206\0\12\24"+
    "\306\0\12\24\234\0\12\24\166\0\12\24\140\0\12\24"+
    "\166\0\12\24\106\0\12\24\u0116\0\12\24\106\0\12\24"+
    "\u0146\0\12\24\46\0\12\24\u012c\0\12\24\200\0\12\24"+
    "\246\0\12\24\6\0\12\24\266\0\12\24\126\0\12\24"+
    "\206\0\12\24\6\0\12\24\316\0\2\1\u01a6\0\12\24"+
    "\46\0\12\24\306\0\12\24\26\0\12\24\126\0\12\24"+
    "\u0196\0\12\24\6\0\u0100\1\240\0\12\24\206\0\12\24"+
    "\u012c\0\12\24\200\0\12\24\74\0\12\24\220\0\12\24"+
    "\166\0\12\24\146\0\12\24\206\0\12\24\106\0\12\24"+
    "\266\0\12\24\u0164\0\62\24\100\0\12\24\266\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[7424];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\3\1\1\2\2\1\1\0\1\3\13\0\1\3"+
    "\5\0\1\4\46\0\1\5\2\0\1\6\45\0\1\7"+
    "\3\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[110];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\25\0\52\0\77\0\25\0\124\0\151\0\176"+
    "\0\223\0\250\0\275\0\322\0\347\0\374\0\u0111\0\u0126"+
    "\0\u013b\0\u0150\0\77\0\u0165\0\25\0\223\0\124\0\151"+
    "\0\u017a\0\u018f\0\25\0\u01a4\0\u01b9\0\u01ce\0\u01e3\0\u01f8"+
    "\0\u020d\0\u0222\0\u0237\0\u024c\0\u0261\0\u0276\0\u028b\0\u02a0"+
    "\0\u02b5\0\u02ca\0\u02df\0\u02f4\0\u0309\0\u031e\0\u0333\0\u0348"+
    "\0\u035d\0\u0372\0\u0387\0\u039c\0\u03b1\0\u03c6\0\u03db\0\u03f0"+
    "\0\u0405\0\u041a\0\u042f\0\u0444\0\u0459\0\u046e\0\u0483\0\u0498"+
    "\0\u04ad\0\25\0\u04c2\0\u04d7\0\25\0\u04ec\0\u0501\0\u0516"+
    "\0\u052b\0\u0540\0\u0555\0\u056a\0\u057f\0\u0594\0\u05a9\0\u05be"+
    "\0\u05d3\0\u05e8\0\u05fd\0\u0612\0\u0627\0\u063c\0\u0651\0\u0666"+
    "\0\u067b\0\u0690\0\u06a5\0\u06ba\0\u06cf\0\u06e4\0\u06f9\0\u070e"+
    "\0\u0723\0\u0738\0\u074d\0\u0762\0\u0777\0\u078c\0\u07a1\0\u07b6"+
    "\0\u07cb\0\u07e0\0\25\0\u07f5\0\u080a\0\u081f";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[110];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\0\1\2\1\3\1\4\1\2\1\5\1\2"+
    "\1\6\1\7\12\2\1\6\25\0\3\10\1\11\1\12"+
    "\2\10\1\13\1\14\1\15\1\10\3\13\1\16\3\13"+
    "\1\17\1\13\1\20\10\0\2\21\12\0\1\21\10\0"+
    "\2\22\12\0\1\22\4\0\1\23\3\0\2\24\12\0"+
    "\1\24\3\10\1\25\21\10\3\0\1\26\1\23\3\0"+
    "\1\27\1\30\12\0\1\27\3\10\1\25\4\10\2\31"+
    "\12\10\1\31\3\10\1\25\3\10\3\13\1\32\11\13"+
    "\4\10\1\33\3\10\1\13\2\34\1\32\11\13\1\35"+
    "\3\10\1\33\1\12\2\10\1\13\2\36\1\32\11\13"+
    "\1\37\3\10\1\25\3\10\3\13\1\32\1\13\1\40"+
    "\7\13\4\10\1\25\3\10\3\13\1\32\5\13\1\41"+
    "\3\13\4\10\1\33\4\10\2\35\12\10\1\35\10\0"+
    "\2\42\12\0\1\42\10\0\2\43\12\0\1\43\10\0"+
    "\2\44\12\0\1\44\3\10\1\25\4\10\2\45\12\10"+
    "\1\45\3\10\1\25\4\10\2\46\1\10\11\46\4\10"+
    "\1\33\3\10\1\13\2\47\1\32\11\13\1\50\3\10"+
    "\1\33\4\10\2\50\12\10\1\50\3\10\1\33\3\10"+
    "\1\13\2\51\1\32\11\13\1\52\3\10\1\33\4\10"+
    "\2\52\12\10\1\52\3\10\1\25\3\10\3\13\1\32"+
    "\4\13\1\53\4\13\4\10\1\25\3\10\3\13\1\32"+
    "\10\13\1\54\1\10\10\0\2\55\12\0\1\55\2\0"+
    "\1\56\5\0\2\57\12\0\1\57\2\0\1\56\5\0"+
    "\2\60\12\0\1\60\3\10\1\25\4\10\2\61\12\10"+
    "\1\61\3\10\1\25\3\10\1\62\2\46\1\10\11\46"+
    "\3\10\1\63\1\33\3\10\1\13\2\64\1\32\11\13"+
    "\1\65\2\10\1\63\1\33\4\10\2\65\12\10\1\65"+
    "\2\10\1\63\1\33\3\10\1\13\2\66\1\32\11\13"+
    "\1\67\2\10\1\63\1\33\4\10\2\67\12\10\1\67"+
    "\3\10\1\25\3\10\3\13\1\32\6\13\1\54\2\13"+
    "\4\10\1\25\3\10\3\13\1\32\2\13\1\70\6\13"+
    "\1\10\5\0\1\43\27\0\2\57\12\0\1\57\10\0"+
    "\2\71\12\0\1\71\2\0\1\56\5\0\2\72\12\0"+
    "\1\72\3\10\1\25\1\10\1\73\22\10\1\25\4\10"+
    "\2\74\1\10\11\74\4\10\1\25\4\10\2\75\12\10"+
    "\1\75\3\10\1\33\3\10\1\13\2\76\1\32\11\13"+
    "\1\77\3\10\1\33\4\10\2\77\12\10\1\77\2\10"+
    "\1\63\1\33\3\10\1\13\2\100\1\32\11\13\1\101"+
    "\2\10\1\63\1\33\4\10\2\101\12\10\1\101\3\10"+
    "\1\102\3\10\3\13\1\32\11\13\1\10\10\0\2\103"+
    "\12\0\1\103\10\0\2\104\12\0\1\104\2\10\1\63"+
    "\1\25\4\10\2\75\12\10\1\75\3\10\1\105\3\10"+
    "\1\106\2\74\1\10\11\74\4\10\1\25\4\10\2\107"+
    "\12\10\1\107\3\10\1\33\3\10\1\13\2\110\1\32"+
    "\11\13\1\111\3\10\1\33\4\10\2\111\12\10\1\111"+
    "\3\10\1\33\3\10\1\13\2\112\1\32\11\13\1\113"+
    "\3\10\1\33\4\10\2\113\12\10\1\113\2\0\1\114"+
    "\5\0\2\115\12\0\1\115\2\0\1\114\5\0\2\116"+
    "\12\0\1\116\3\10\1\25\4\10\2\117\1\10\11\117"+
    "\4\10\1\25\4\10\2\120\12\10\1\120\2\10\1\121"+
    "\1\33\3\10\1\13\2\122\1\32\11\13\1\123\2\10"+
    "\1\121\1\33\4\10\2\123\12\10\1\123\2\10\1\121"+
    "\1\33\3\10\1\13\2\124\1\32\11\13\1\125\2\10"+
    "\1\121\1\33\4\10\2\125\12\10\1\125\10\0\2\115"+
    "\12\0\1\115\10\0\2\126\12\0\1\126\2\0\1\114"+
    "\5\0\2\127\12\0\1\127\3\10\1\105\4\10\2\117"+
    "\1\10\11\117\3\10\1\121\1\25\4\10\2\130\12\10"+
    "\1\130\3\10\1\25\4\10\2\130\12\10\1\130\3\10"+
    "\1\33\3\10\1\13\2\131\1\32\11\13\1\132\3\10"+
    "\1\33\4\10\2\132\12\10\1\132\2\10\1\121\1\33"+
    "\3\10\1\13\2\133\1\32\11\13\1\134\2\10\1\121"+
    "\1\33\4\10\2\134\12\10\1\134\10\0\2\135\12\0"+
    "\1\135\10\0\2\136\12\0\1\136\3\10\1\25\4\10"+
    "\2\137\12\10\1\137\3\10\1\33\3\10\1\13\2\140"+
    "\1\32\11\13\1\141\3\10\1\33\4\10\2\141\12\10"+
    "\1\141\3\10\1\33\3\10\1\13\2\142\1\32\11\13"+
    "\1\143\3\10\1\33\4\10\2\143\12\10\1\143\10\0"+
    "\2\144\12\0\1\144\10\0\2\145\12\0\1\145\3\10"+
    "\1\25\4\10\2\146\12\10\1\146\3\10\1\33\3\10"+
    "\1\13\2\147\1\32\11\13\1\150\3\10\1\33\4\10"+
    "\2\150\12\10\1\150\3\10\1\33\3\10\1\13\2\151"+
    "\1\32\11\13\1\152\3\10\1\33\4\10\2\152\12\10"+
    "\1\152\3\0\1\153\24\0\1\153\4\0\2\144\12\0"+
    "\1\144\3\10\1\25\4\10\2\154\12\10\1\154\3\10"+
    "\1\153\3\10\1\13\2\155\1\32\11\13\1\156\3\10"+
    "\1\153\4\10\2\156\12\10\1\156\3\10\1\153\3\10"+
    "\1\13\2\147\1\32\11\13\1\150\3\10\1\153\4\10"+
    "\2\150\12\10\1\150\3\10\1\153\24\10\1\33\3\10"+
    "\1\13\2\155\1\32\11\13\1\156\3\10\1\33\4\10"+
    "\2\156\12\10\1\156";

  private static int [] zzUnpacktrans() {
    int [] result = new int[2100];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\1\11\2\1\1\0\1\1\13\0"+
    "\1\11\5\0\1\11\46\0\1\11\2\0\1\11\45\0"+
    "\1\11\3\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[110];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Scanner(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public String nextToken() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
          { return "EOF";
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return "UNREC " + yytext();
            }
          // fall through
          case 8: break;
          case 2:
            { return "SEP " + yytext();
            }
          // fall through
          case 9: break;
          case 3:
            { return "QUOTE " + yytext();
            }
          // fall through
          case 10: break;
          case 4:
            { return "DIGIT " + yytext();
            }
          // fall through
          case 11: break;
          case 5:
            { return "BOOL " + yytext();
            }
          // fall through
          case 12: break;
          case 6:
            { return "EMAIL " + yytext();
            }
          // fall through
          case 13: break;
          case 7:
            { return "PHONE " + yytext();
            }
          // fall through
          case 14: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
