# MIPS assembly autogenerated by compiler
#
# @author Grant Yang
# @version 2024-05-16T14:12:29.345358

.macro push %reg
	sw %reg ($sp)
	addi $sp $sp -4
.end_macro
.macro pop %reg
	addi $sp $sp 4
	lw %reg ($sp)
.end_macro

.macro push.d %reg
	mfc1.d $t6 %reg
    sw $t6 -4($sp)
    sw $t7 ($sp)
    addi $sp $sp -8
.end_macro
.macro pop.d %reg
	addi $sp $sp 8
    lw $t6 -4($sp)
    lw $t7 ($sp)
    mtc1.d $t6 %reg
.end_macro

.data
data0: .double 0.0
_pi: .double 0.0
data1: .double 4.0
_parity: .double 0.0
_i: .word 0
data2: .double 1.0

.text 0x00400000
.globl main
main:
	l.d $f0 data0 # literal float: 0.0
	push.d $f0
	la $s0 _pi # variable
	pop.d $f0
	mfc1 $t6 $f0
	sd $t6 ($s0) # binop ($pi := #0.0)
	l.d $f0 data1 # literal float: 4.0
	push.d $f0
	la $s0 _parity # variable
	pop.d $f0
	mfc1 $t6 $f0
	sd $t6 ($s0) # binop ($parity := #4.0)
	# begin for loop 2
	# WARNING, ERR, not impl: current FOR impl corrupts the stack on RETURN/EXIT
	li $v0 0 # literal number
	push $v0
	la $s0 _i # variable
	pop $v0
	sw $v0 ($s0) # binop ($i := #0)
	# for loop 2
	push $s0
	push $v0
	li $v0 10 # literal number
	pop $t0
	push $v0
forLoop2:
	bge $t0 $v0 exit_forLoop2
	la $s0 _pi # variable
	ld $t6 ($s0)
	mtc1.d $t6 $f0 # var load
	push.d $f0
	la $s0 _parity # variable
	ld $t6 ($s0)
	mtc1.d $t6 $f0 # var load
	push.d $f0
	la $s0 _i # variable
	lw $v0 ($s0) # var load
	push $v0
	li $v0 2 # literal number
	pop $t0
	mul $v0 $t0 $v0 # binop ($i * #2)
	mtc1 $v0 $f0
	cvt.d.w $f0 $f0
	push.d $f0
	l.d $f0 data2 # literal float: 1.0
	pop.d $f2
	add.d $f0 $f2 $f0 # binop (($i * #2) + #1.0)
	pop.d $f2
	div.d $f0 $f2 $f0 # binop ($parity / (($i * #2) + #1.0))
	pop.d $f2
	add.d $f0 $f2 $f0 # binop ($pi + ($parity / (($i * #2) + #1.0)))
	push.d $f0
	la $s0 _pi # variable
	pop.d $f0
	mfc1 $t6 $f0
	sd $t6 ($s0) # binop ($pi := ($pi + ($parity / (($i * #2) + #1.0))))
	la $s0 _parity # variable
	ld $t6 ($s0)
	mtc1.d $t6 $f0 # var load
	push.d $f0
	l.d $f0 data2 # literal float: 1.0
	neg.d $f0 $f0 # unary op -(#1.0)
	pop.d $f2
	mul.d $f0 $f2 $f0 # binop ($parity * -(#1.0))
	push.d $f0
	la $s0 _parity # variable
	pop.d $f0
	mfc1 $t6 $f0
	sd $t6 ($s0) # binop ($parity := ($parity * -(#1.0)))
	la $s0 _pi # variable
	ld $t6 ($s0)
	mtc1.d $t6 $f0 # var load
	mov.d $f12 $f0
	li $v0 3
	syscall # WRITE double $pi
	li $v0 11
	li $a0 10
	syscall # newline from WRITELN
	# for loop 2 update loop variable
	lw $s0 8($sp)
	lw $v0 4($sp)
	lw $t0 ($s0)
	addi $t0 $t0 1
	sw $t0 ($s0)
	j forLoop2
exit_forLoop2:
	addi $sp $sp 8
	# end for loop 2
return_main:
immediateReturn_main:
	li $v0 10
	syscall

