import os
import torch
import torch.nn.functional as F
from charmodel import CharModel, ModelArgs, visualize

# ==============================================================================
# Hyperparameters
# ==============================================================================
model_path = 'model_final.pt'
max_seq_len = 4096
n_layers = 24
prompt = '\x00' + """
// Rotartsi function to prove cantor's theorem
NOT_SURJECTIVE under_cantor(FUNCPTR (*f)(int), char *p_name) {
"""
max_new_tokens = 4096
temperature = 0.8
top_k = 40

device = 'cuda' if torch.cuda.is_available() else 'cpu'
if not torch.cuda.is_available() and torch.backends.mps.is_available():
    device = 'mps'

# ==============================================================================
# Model Loading
# ==============================================================================
if not os.path.exists(model_path):
    print(f"Error: {model_path} not found. Please train the model first.")
    exit(1)

print(f"Loading model on {device}...")
args = ModelArgs(max_seq_len=max_seq_len, n_layers=n_layers)
model = CharModel(args)

checkpoint = torch.load(model_path, map_location=device, weights_only=True)

# Remove the '_orig_mod.' prefix added by torch.compile during training
unwanted_prefix = '_orig_mod.'
for k, v in list(checkpoint.items()):
    if k.startswith(unwanted_prefix):
        checkpoint[k[len(unwanted_prefix):]] = checkpoint.pop(k)

model.load_state_dict(checkpoint)

visualize(model.named_parameters(), fname="vis_linuz/")
with open("model_linux.bin", "wb") as fp:
    fp.write(model.dump_bytes())

model.to(device)
model.eval()

# ==============================================================================
# Generation Function
# ==============================================================================
@torch.no_grad()
def generate(model, idx, max_new_tokens, temperature=1.0, top_k=None):
    """
    Takes a conditioning sequence of indices idx (LongTensor of shape (b,t))
    and yields the next generated byte index one by one.
    """
    for _ in range(max_new_tokens):
        # crop idx to the max_seq_len if it exceeds it. Keep the first token as the attention sink.
        if idx.size(1) <= max_seq_len:
            idx_cond = idx
        else:
            idx_cond = torch.cat([idx[:, :1], idx[:, -(max_seq_len - 1):]], dim=1)
        
        # forward pass
        logits, _ = model(idx_cond)
        
        # pluck the logits at the final step and scale by temperature
        logits = logits[:, -1, :] / temperature
        
        # optionally crop the logits to only the top k options
        if top_k is not None:
            v, _ = torch.topk(logits, min(top_k, logits.size(-1)))
            logits[logits < v[:, [-1]]] = -float('Inf')
            
        # apply softmax to convert logits to (normalized) probabilities
        probs = F.softmax(logits, dim=-1)
        
        # sample from the distribution
        idx_next = torch.multinomial(probs, num_samples=1)
        
        # append sampled index to the running sequence
        idx = torch.cat((idx, idx_next), dim=1)
        
        yield idx_next.item()

# ==============================================================================
# Inference Execution
# ==============================================================================
# Encode prompt to raw bytes
encoded_prompt = list(prompt.encode('utf-8'))
idx = torch.tensor([encoded_prompt], dtype=torch.long).to(device)

print("\n--- Generating Text ---\n")
print(prompt, end="", flush=True)

output_bytes = bytearray()
stream_buffer = bytearray()

for new_byte in generate(model, idx, max_new_tokens, temperature, top_k):
    output_bytes.append(new_byte)
    stream_buffer.append(new_byte)
    
    # Try to decode the stream buffer. 
    # If it's a valid UTF-8 sequence, print it and clear the buffer.
    # If it fails, it might be the start of a multi-byte character (like an emoji),
    # so we just keep accumulating until it's valid.
    try:
        decoded_char = stream_buffer.decode('utf-8')
        print(decoded_char, end="", flush=True)
        stream_buffer.clear()
    except UnicodeDecodeError:
        pass

print("\n\n--- Generation Complete ---")

# In case the model ends on an invalid byte sequence, you can safely decode 
# the full final string by replacing invalid errors
final_bytes = prompt.encode('utf-8') + output_bytes
print("\nFinal Decoded String (with safety replacement for invalid bytes):")
print(final_bytes.decode('utf-8', errors='replace'))
