# MIPS assembly autogenerated by compiler
#
# @author Grant Yang
# @version 2024-05-16T14:12:29.307805

.macro push %reg
	sw %reg ($sp)
	addi $sp $sp -4
.end_macro
.macro pop %reg
	addi $sp $sp 4
	lw %reg ($sp)
.end_macro

.macro push.d %reg
	mfc1.d $t6 %reg
    sw $t6 -4($sp)
    sw $t7 ($sp)
    addi $sp $sp -8
.end_macro
.macro pop.d %reg
	addi $sp $sp 8
    lw $t6 -4($sp)
    lw $t7 ($sp)
    mtc1.d $t6 %reg
.end_macro

.data
_i: .word 0
data0: .double 1.0
data1: .asciiz ""
data2: .double 7.0
data3: .double 0.0

.text 0x00400000
.globl main
main:
	# begin for loop 0
	# WARNING, ERR, not impl: current FOR impl corrupts the stack on RETURN/EXIT
	li $v0 0 # literal number
	push $v0
	la $s0 _i # variable
	pop $v0
	sw $v0 ($s0) # binop ($i := #0)
	# for loop 0
	push $s0
	push $v0
	li $v0 10 # literal number
	pop $t0
	push $v0
forLoop0:
	bge $t0 $v0 exit_forLoop0
	la $s0 _i # variable
	lw $v0 ($s0) # var load
	move $a0 $v0
	li $v0 1
	syscall # WRITE int $i
	li $v0 11
	li $a0 10
	syscall # newline from WRITELN
	# procedure call: fib[$i]
	addi $sp $sp -8
	# fib argument 0: n
	la $s0 _i # variable
	lw $v0 ($s0) # var load
	push $v0
	addi $sp $sp 12
	jal proc_fib
	move $a0 $v0
	li $v0 1
	syscall # WRITE int fib[$i]
	li $v0 11
	li $a0 10
	syscall # newline from WRITELN
	# procedure call: factorialf[($i * #1.0)]
	addi $sp $sp -8
	# factorialf argument 0: i
	la $s0 _i # variable
	lw $v0 ($s0) # var load
	mtc1 $v0 $f0
	cvt.d.w $f0 $f0
	push.d $f0
	l.d $f0 data0 # literal float: 1.0
	pop.d $f2
	mul.d $f0 $f2 $f0 # binop ($i * #1.0)
	push.d $f0
	addi $sp $sp 16
	jal proc_factorialf
	mov.d $f12 $f0
	li $v0 3
	syscall # WRITE double factorialf[($i * #1.0)]
	li $v0 11
	li $a0 10
	syscall # newline from WRITELN
	la $a0 data1 # literal string
	li $v0 4
	syscall # WRITE string parser.Parser$10@49c2faae
	li $v0 11
	li $a0 10
	syscall # newline from WRITELN
	# for loop 0 update loop variable
	lw $s0 8($sp)
	lw $v0 4($sp)
	lw $t0 ($s0)
	addi $t0 $t0 1
	sw $t0 ($s0)
	j forLoop0
exit_forLoop0:
	addi $sp $sp 8
	# end for loop 0
return_main:
immediateReturn_main:
	li $v0 10
	syscall
proc_factorial:
	sw $fp ($sp)
	sw $ra -4($sp)
	move $fp $sp
	addi $sp $sp -12

	# real function body for factorial
	# begin if condition 1
	addi $s0 $fp -8 # variable i
	lw $v0 ($s0) # var load
	push $v0
	li $v0 0 # literal number
	pop $t0
	seq $v0 $t0 $v0 # binop ($i = #0)
	beqz $v0 elseOf_if1
if1:
	li $v0 1 # literal number
	j immediateReturn_factorial
	j continueAfter_if1
elseOf_if1:
	addi $s0 $fp -8 # variable i
	lw $v0 ($s0) # var load
	push $v0
	# procedure call: factorial[($i - #1)]
	addi $sp $sp -8
	# factorial argument 0: i
	addi $s0 $fp -8 # variable i
	lw $v0 ($s0) # var load
	push $v0
	li $v0 1 # literal number
	pop $t0
	sub $v0 $t0 $v0 # binop ($i - #1)
	push $v0
	addi $sp $sp 12
	jal proc_factorial
	pop $t0
	mul $v0 $t0 $v0 # binop ($i * factorial[($i - #1)])
	j immediateReturn_factorial
continueAfter_if1:
return_factorial:
	# no return value
immediateReturn_factorial:
	move $sp $fp
	lw $ra -4($sp)
	lw $fp ($sp)
	jr $ra
proc_factorialf:
	sw $fp ($sp)
	sw $ra -4($sp)
	move $fp $sp
	addi $sp $sp -24

	# real function body for factorialf
	l.d $f0 data2 # literal float: 7.0
	push.d $f0
	addi $s0 $fp -20 # variable factorialf
	pop.d $f0
	mfc1 $t6 $f0
	sd $t6 ($s0) # binop ($factorialf := #7.0)
	# begin if condition 2
	addi $s0 $fp -12 # variable i
	ld $t6 ($s0)
	mtc1.d $t6 $f0 # var load
	push.d $f0
	l.d $f0 data3 # literal float: 0.0
	pop.d $f2
	move $v0 $0
	li $t0 1
	c.eq.d $f2 $f0
	movt $v0 $t0 # binop ($i = #0.0)
	beqz $v0 elseOf_if2
if2:
	l.d $f0 data0 # literal float: 1.0
	j immediateReturn_factorialf
	j continueAfter_if2
elseOf_if2:
	addi $s0 $fp -12 # variable i
	ld $t6 ($s0)
	mtc1.d $t6 $f0 # var load
	push.d $f0
	# procedure call: factorialf[($i - #1)]
	addi $sp $sp -8
	# factorialf argument 0: i
	addi $s0 $fp -12 # variable i
	ld $t6 ($s0)
	mtc1.d $t6 $f0 # var load
	push.d $f0
	li $v0 1 # literal number
	mtc1 $v0 $f0
	cvt.d.w $f0 $f0
	pop.d $f2
	sub.d $f0 $f2 $f0 # binop ($i - #1)
	push.d $f0
	addi $sp $sp 16
	jal proc_factorialf
	pop.d $f2
	mul.d $f0 $f2 $f0 # binop ($i * factorialf[($i - #1)])
	j immediateReturn_factorialf
continueAfter_if2:
return_factorialf:
	addi $s0 $fp -20 # variable factorialf
	ld $t6 ($s0)
	mtc1.d $t6 $f0 # var load
immediateReturn_factorialf:
	move $sp $fp
	lw $ra -4($sp)
	lw $fp ($sp)
	jr $ra
proc_fib:
	sw $fp ($sp)
	sw $ra -4($sp)
	move $fp $sp
	addi $sp $sp -16

	# real function body for fib
	# begin if condition 0
	addi $s0 $fp -8 # variable n
	lw $v0 ($s0) # var load
	push $v0
	li $v0 1 # literal number
	pop $t0
	sle $v0 $t0 $v0 # binop ($n <= #1)
	beqz $v0 elseOf_if0
if0:
	li $v0 1 # literal number
	j immediateReturn_fib
	j continueAfter_if0
elseOf_if0:
	# no op
continueAfter_if0:
	# procedure call: fib[($n - #1)]
	addi $sp $sp -8
	# fib argument 0: n
	addi $s0 $fp -8 # variable n
	lw $v0 ($s0) # var load
	push $v0
	li $v0 1 # literal number
	pop $t0
	sub $v0 $t0 $v0 # binop ($n - #1)
	push $v0
	addi $sp $sp 12
	jal proc_fib
	push $v0
	# procedure call: fib[($n - #2)]
	addi $sp $sp -8
	# fib argument 0: n
	addi $s0 $fp -8 # variable n
	lw $v0 ($s0) # var load
	push $v0
	li $v0 2 # literal number
	pop $t0
	sub $v0 $t0 $v0 # binop ($n - #2)
	push $v0
	addi $sp $sp 12
	jal proc_fib
	pop $t0
	add $v0 $t0 $v0 # binop (fib[($n - #1)] + fib[($n - #2)])
	push $v0
	addi $s0 $fp -12 # variable fib
	pop $v0
	sw $v0 ($s0) # binop ($fib := (fib[($n - #1)] + fib[($n - #2)]))
return_fib:
	addi $s0 $fp -12 # variable fib
	lw $v0 ($s0) # var load
immediateReturn_fib:
	move $sp $fp
	lw $ra -4($sp)
	lw $fp ($sp)
	jr $ra

